-- MySQL Script generated by MySQL Workbench
-- 03/27/24 21:34:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema techborrow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techborrow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techborrow` DEFAULT CHARACTER SET utf8 ;
USE `techborrow` ;

-- -----------------------------------------------------
-- Table `techborrow`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`usuario` (
  `matricula` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techborrow`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`material` (
  `numeroControl` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`numeroControl`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techborrow`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`solicitante` (
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `hora` TIME(5) NULL,
  `maestroRes` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techborrow`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`prestamo` (
    `numeroPrestamo` INT NOT NULL AUTO_INCREMENT,
    `numeroControl` INT NOT NULL,
    `tipo` VARCHAR(45) NULL,
    `matricula` VARCHAR(45) NOT NULL,
    `nombre` VARCHAR(45) NULL,
    `fecha` DATETIME NULL,
    `hora` TIME(5) NULL,
    `maestroRes` VARCHAR(45) NULL,
    PRIMARY KEY (`numeroPrestamo`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `techborrow`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`devolucion` (
  `numeroDevolucion` INT NOT NULL,
  `numeroControl` INT NULL,
  `comentarios` VARCHAR(45) NULL,
  PRIMARY KEY (`numeroDevolucion`),
  INDEX `numeroControl_idx` (`numeroControl` ASC),
  CONSTRAINT `numeroControl`
    FOREIGN KEY (`numeroControl`)
    REFERENCES `techborrow`.`material` (`numeroControl`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
