-- MySQL Script generated by MySQL Workbench
-- 04/01/24 03:24:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema techborrow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techborrow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techborrow` DEFAULT CHARACTER SET utf8 ;
USE `techborrow` ;

-- -----------------------------------------------------
-- Table `techborrow`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`material` (
  `numeroControl` VARCHAR(11) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `estado` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`numeroControl`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techborrow`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`prestamo` (
  `numeroPrestamo` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroControl` VARCHAR(11) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `hora` TIME(5) NULL DEFAULT NULL,
  `maestroRes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numeroPrestamo`, `numeroControl`, `matricula`),
  INDEX `numeroControl_idx` (`numeroControl` ASC),
  INDEX `FK_numeroControl_idx` (`numeroControl` ASC),
  INDEX `FK_matricula_idx` (`matricula` ASC),
  CONSTRAINT `FK_matricula`
    FOREIGN KEY (`matricula`)
    REFERENCES `techborrow`.`solicitante` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_numeroControl`
    FOREIGN KEY (`numeroControl`)
    REFERENCES `techborrow`.`material` (`numeroControl`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techborrow`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`devolucion` (
  `numeroDevolucion` INT(11) NOT NULL,
  `numeroControl` INT(11) NULL DEFAULT NULL,
  `comentarios` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numeroDevolucion`),
  INDEX `numeroControl_idx` (`numeroControl` ASC),
  CONSTRAINT `FK_numerocontrol`
    FOREIGN KEY (`numeroControl`)
    REFERENCES `techborrow`.`prestamo` (`numeroControl`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techborrow`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techborrow`.`usuario` (
  `matricula` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `contra` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
